### ISSUE TITLE
AIMPを開いた状態でないと、TrackInfo CurrentTrack で例外が発生し落ちる

### ISSUE THREAD

**Issue by Asteriskx** [Legato-Dev/Legato#23]
public static TrackInfo CurrentTrack
　
  - MemoryMappedFile.OpenExisting で例外発生。
　・'System.IO.FileNotFoundException (System.Core.dll )

Legato.TwitterSample を起動した時に、非同期で AIMP を立ち上げるか、
CurrentTrack を null を返すか
適当な例外を返す仕様にするべき。

**Comment by marihachi** [comment]
投げなおしました
