### ISSUE TITLE
Legato.Twitter.Sample でアルバムアートがない時の挙動を検討する

### ISSUE THREAD

**Issue by Asteriskx** [Legato-Dev/Legato#25]

**Comment by Asteriskx** [comment]
アルバムアートがない時は、Legato のロゴを UI 表示・Twitter へ投稿するように実装する。

**Comment by Asteriskx** [comment]
実装中
2回目以降の挙動が微妙なので、調整します

**Comment by Asteriskx** [comment]
Token べた書きしていたので、いったんアプリごと削除。
要再登録。

**Comment by marihachi** [comment]
今の実装だとAlbumArtが無ければLegatoのロゴを投稿してるけど、

Twitterでも言ったように、
AlbumArtが無ければ **「アルバムアートも投稿」がチェックされた状態でもテキストのみを投稿** するようにしない？

意見欲しい

**Comment by Asteriskx** [comment]
UI 上だけロゴを使用する形にするってこと？
Twitter 上には投稿したくないってことね。
個人の好みな気がしてますね。
では、テキストのみの投稿にしますか。

**Comment by marihachi** [comment]
好みか... うーん

**Comment by marihachi** [comment]
投稿しないほうがユーザーの驚きが少ない気がするし、投稿しないようにしよう

**Comment by marihachi** [comment]
ok
