### ISSUE TITLE
v1.1 リリース

### ISSUE THREAD

**Issue by marihachi** [Legato-Dev/Legato#29]
しますか
ある程度状況が安定してきたらNuGetも含めてリリース

**Comment by Asteriskx** [comment]
そろそろリリースしたいけど、#30 があるからちょっと待とう

**Comment by Asteriskx** [comment]
ちょっと色々誤算があって、先にリリースされてしまったので、
Ver.1.1 リリースで次の対応織り込み。

**Comment by marihachi** [comment]
## v1.1で対応予定のissues
- [x] Legatoクラスをリネーム(Legato → Aimp) #43 
- [x] Legatoクラスの分離
  - [x] 通知イベントの分離(クラス化) #7 
- [x] AlbumArtExtractionのプロジェクトからの分離とLegatoのアルバムアート取得のサポート廃止 #53 
## もはや対応されなくなったissues
- [x] ~~AlbumArtExtractionでfilePathのファイルパスが無効なとき(URLなど)処理をスキップするように#46~~ 
- [ ] ~~稀にアルバムアートが前の曲から更新されない #30~~ 
  - [ ] ~~ID3タグへの対応 #32~~ 
- [x] ~~DirectoryAlbumArtExtractorの挙動変更 #44~~

**Comment by Asteriskx** [comment]
ID3 対応できた（残件はあるけど）ので、リリースします？

**Comment by marihachi** [comment]
していこう

**Comment by marihachi** [comment]
もうすぐ公開されます
