### ISSUE TITLE
タグ情報からアルバムアートを取得する処理をライブラリとしてまとめる事への検討

### ISSUE THREAD

**Issue by marihachi** [Legato-Dev/Legato#33]
アルバムアートを音声ファイルのタグ情報から取ってくる処理を書くのであれば、それだけでライブラリとして成り立ちそうだし、分離して開発してもよさそう

どうかな

**Comment by Asteriskx** [comment]
良いと思います〜

**Comment by marihachi** [comment]
AlbumArtExtractionプロジェクトとして独立しました
