### ISSUE TITLE
ライブラリが独自にアルバムアートを取得することによって、AIMPの「アルバムアートの自動検索」機能の恩恵が受けられない問題

### ISSUE THREAD

**Issue by marihachi** [Legato-Dev/Legato#34]
仕方ないね

- インターネットから自動的に取得
- 同ディレクトリからそれらしい画像ファイルの取得(cover, folder 等の名前の画像の検索)

これも独自実装することになりそうかな？？
また、その実装は必要かな？

## 関連
- #35 ディレクトリから
- #38 インターネットから

**Comment by Asteriskx** [comment]
AIMP が自分でやる機能ではなく、独自に追加するってことね
あれば、便利だとは思うけど...

**Comment by marihachi** [comment]
ンー

**Comment by marihachi** [comment]
まあ今の https://github.com/Legato-Dev/Legato/projects/1 が落ち着いてきたら検討していこう

**Comment by marihachi** [comment]
自動検索機能の一部である、ディレクトリからの抽出を実装することにした #35
