### ISSUE TITLE
FLAC 音源にて取得したアルバムアートが曲と無関係なものが取得される場合がある

### ISSUE THREAD

**Issue by Asteriskx** [Legato-Dev/Legato#37]
わけわかめ(´めωめ`*)

**Comment by marihachi** [comment]
ディレクトリから取りに行ってるとか？

**Comment by Asteriskx** [comment]
かもしれない
ない場合は、勝手に取得されるのかも

**Comment by Asteriskx** [comment]
やっかいな仕様だぜ～～

**Comment by marihachi** [comment]
てか、意図的にFlacで且つアルバムアートが保存されていない場合は、DirectoryAlbumArtExtractorで引っかかるようにしてるから..

**Comment by marihachi** [comment]
対応策として、DirectoryAlbumArtExtractorで使われている条件をもう少し限定的なものにする、とかになるかな

**Comment by Asteriskx** [comment]
今ぱっと思いついた案としては、
やっぱりネット上検索して、取得できるようしたいなーなんて

**Comment by Asteriskx** [comment]
無茶ぶり案件

**Comment by marihachi** [comment]
ア～ｗｗｗ

**Comment by Asteriskx** [comment]
曲名取得できてるから、それをキーにして

**Comment by Asteriskx** [comment]
ビッグデータの扱いに長けてるC#なら問題ないでしょ（慢心）

**Comment by marihachi** [comment]
誤動作する可能性は他の取得方法よりも遥かに高い

**Comment by Asteriskx** [comment]
ですよねぇ。

**Comment by Asteriskx** [comment]
ちょっとやってみるか。
個人的にだけど

**Comment by marihachi** [comment]
やったぜ。

**Comment by Asteriskx** [comment]
平日は最近疲れがヤバいので
土日にしか活動無理ゲになりつつありまする

**Comment by marihachi** [comment]
それが出来たら、DirectoryAlbumArtExtractorの次のレイヤーとして置く？

**Comment by Asteriskx** [comment]
上手く動いてくれたらね！！！！

**Comment by marihachi** [comment]
せやな

**Comment by marihachi** [comment]
#38

**Comment by marihachi** [comment]
それで、無関係なものが取得される場合だけど、DirectoryAlbumArtExtractorが誤作動しているってことであってた？
Legato.Legato.AlbumArtのreturn前にデバッグコード書いてあるからどのAlbumArtExtractorが使われているか分かると思うんだけど

**Comment by Asteriskx** [comment]
多分その認識で合ってると思う

**Comment by marihachi** [comment]
わかった

**Comment by marihachi** [comment]
移動
-> #44
