### ISSUE TITLE
曲再生時、変更時に曲名等をバルーン通知でも表示する

### ISSUE THREAD

**Issue by Asteriskx** [Legato-Dev/Legato#39]
SoundCloud がそんな感じなのよね

**Comment by Asteriskx** [comment]
notifyIcon コントロールをUIにセットすればよいよ

**notifyIcon.BalloonTipTitle = "曲名ーアルバム名";**
**notifyIcon.BalloonTipText = アーティスト名;**
**notifyIcon.ShowBalloonTip(2000); // 通知表示時間**

確かWindows 10から、画像もバルーン通知に含めることが出来たと思う

**Comment by Asteriskx** [comment]
こんな感じで考えてるので、ちょいと実装してみますわ

**Comment by Asteriskx** [comment]
OK

**Comment by Asteriskx** [comment]
コミットしたら閉じますので～

**Comment by marihachi** [comment]
あい～
