### ISSUE TITLE
一つのディレクトリに複数のアルバムの曲が入っていた場合、DirectoryAlbumArtExtractorが誤ったアルバムアートを使ってしまう可能性がある

### ISSUE THREAD

**Issue by marihachi** [Legato-Dev/Legato#44]
ユーザーによるデータの管理の仕方によっては、DirectoryAlbumArtExtractorが利用できない場面もあるだろうけれど、その際の誤作動はせめて防ぎたい

**Comment by Asteriskx** [comment]
これも報告出来てなかった問題ですね～～ｗｗ

**Comment by marihachi** [comment]
や、これはそれっぽい見当はついてたよー

**Comment by Asteriskx** [comment]
多分これ、Dir 読み込み自体の処理が微妙な希ガス

**Comment by marihachi** [comment]
Directory Ext.を修正することになりそうね

**Comment by Asteriskx** [comment]
Windows がクソなだけかもｗｗｗｗ

**Comment by marihachi** [comment]
とりあえずの実装として、ファイル数が50より多いディレクトリに対してはアルバムアートを返さないように変更します
