### ISSUE TITLE
ネットワークドライブから曲情報を読み込む際、遅延が発生し、mp3 再生エラー・例外が同時発生する

### ISSUE THREAD

**Issue by Asteriskx** [Legato-Dev/Legato#45]
僕の環境（ＮＡＳ）で再現済み

**Comment by marihachi** [comment]
なにそれやばくね

**Comment by marihachi** [comment]
詳細ほしい

**Comment by Asteriskx** [comment]
NAS の稼働状況にもよるっぽいんだけど、
- NAS 上の曲を再生しようとすると、Legato-NowPlaying が固まる
- 固まった場合、再起動することで再生が可能になる
詳細はもうちょっと待って

**Comment by Asteriskx** [comment]
Legato-NowPlaying 側の問題ですので、移動します。
