### ISSUE TITLE
Remote API のメモリ読出し(FetchAlbumArtAsync)でHelper.RequestAlbumArtが失敗した後、メモリ呼び出し経由のアルバムアート取得が一切利用できなくなる不具合

### ISSUE THREAD

**Issue by marihachi** [Legato-Dev/Legato#52]
恐らく、AIMP上でもアルバムアートが設定されていない場合にHelper.RequestAlbumArtが失敗するようです(？)
Receiverを再生成＋通知登録(Helper.RegisterNotify)をし直しても状況は変わらず。

**Comment by Asteriskx** [comment]
一度取得失敗したら、もう取得不可の状態で固着する認識で合ってる？

**Comment by marihachi** [comment]
そうだね

**Comment by marihachi** [comment]
よく分からないけど、RequestAlbumArt()失敗時の_CopyDataMessageReceivedイベントハンドラの解除忘れが原因でした

**Comment by marihachi** [comment]
謎すぎる...
