### ISSUE TITLE
Legato のライブラリ範囲について

### ISSUE THREAD

**Issue by Asteriskx** [Legato-Dev/Legato#53]
現状、
- AlbumArt
- TwitterSample 
を含有した状態で公開してるけど、
Legato として、そこまでするべきか？って疑問に思ってます。

各Sample 毎にリポジトリ分けたりとかどうでしょうかね。。

**Comment by marihachi** [comment]
それぞれ、他のリポジトリへ分離しても良いかもしれませんね。

AlbumArtExtractionの必要性に関して、ぼくは必要だと思ってます。
Remote APIを経由したアルバムアートの取得では正常な結果を得られない可能性が少なからずあるからです。
これに関しては議論の余地がありそうですが

SampleやTwitterSampleの分離に関しては、NuGetからライブラリをインポートして正常に利用できるようになるまでは、実現できないかもしれません。

理想的なリポジトリ構成は:
- Legato (Legato.AlbumArtExtractionに依存)
- Legato.AlbumArtExtraction
- Legato.Sample (Legatoに依存)
- Legato.TwitterSample (Legatoに依存)

のような形かなと個人的に思っています。

ちなみに、NuGetはプロジェクト単位なので既に分離して利用できるようになっています。

**Comment by Asteriskx** [comment]
12/17 現在、`Legato.AlbumArtExtraction` を Legato から完全分離する方針になりました。
ですので、Legato 自身はテキストベースの取得のみとなります。
`Legato.AlbumArtExtraction` はLegato-Dev 内の管轄という部分は変更ありません。

**Comment by marihachi** [comment]
決定したので閉じますね
