### ISSUE TITLE
AIMPが閉じられると多数の例外が発生する

### ISSUE THREAD

**Issue by marihachi** [Legato-Dev/Legato#56]

**Comment by marihachi** [comment]
https://github.com/Legato-Dev/Legato/blob/master/Legato/AimpObserver.cs#L107-L130

AimpObserver.Unsubscribe()がAIMPが閉じられたタイミングで呼び出されるようになっていて、UnsubscribeでAIMPが実行中かどうかの確認をせずにコマンドを送信していた。
AIMPの起動状態の確認を追加して多数の例外が出なくなったことを確認した。

**Comment by Asteriskx** [comment]
あ、コミットしてくれたのね。有難う。
こっちも対応してたけど、コミットしてくれたから取り下げとくわ。

**Comment by marihachi** [comment]
マジか

**Comment by Asteriskx** [comment]
ｂ
