### ISSUE TITLE
各種通知の切り分け検討

### ISSUE THREAD

**Issue by Asteriskx** [Legato-Dev/Legato#7]
CommunicationWindow を介して、各種情報を取得する。
その際、通知が複数になるため、通知クラスを作成すべき？

**Comment by Asteriskx** [comment]
イベントが`CommunicationWindow` 内に固まって定義されてるので、
イベントをイベントクラスとして再定義したい

**Comment by marihachi** [comment]
- CommunicationWindowから通知イベントを分離してクラス化
- Aimpクラス(旧Legatoクラス)からその分離したクラスをインスタンス化して利用する
- Aimpクラスに各種通知イベントを追加する

**Comment by marihachi** [comment]
関連 #49

**Comment by marihachi** [comment]
通知を扱うクラスとしてAimpObserverが追加されました
